sonar.organization= moritzdav
sonar.projectKey= MoritzDav_sopra-fs26-group-04-client

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./app
